package UpperCaseModule;


/**
* UpperCaseModule/UpperCaseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperCase.idl
* Tuesday, 5 May, 2026 10:40:17 PM IST
*/

abstract public class UpperCaseHelper
{
  private static String  _id = "IDL:UpperCaseModule/UpperCase:1.0";

  public static void insert (org.omg.CORBA.Any a, UpperCaseModule.UpperCase that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static UpperCaseModule.UpperCase extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (UpperCaseModule.UpperCaseHelper.id (), "UpperCase");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static UpperCaseModule.UpperCase read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_UpperCaseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, UpperCaseModule.UpperCase value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static UpperCaseModule.UpperCase narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof UpperCaseModule.UpperCase)
      return (UpperCaseModule.UpperCase)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      UpperCaseModule._UpperCaseStub stub = new UpperCaseModule._UpperCaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static UpperCaseModule.UpperCase unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof UpperCaseModule.UpperCase)
      return (UpperCaseModule.UpperCase)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      UpperCaseModule._UpperCaseStub stub = new UpperCaseModule._UpperCaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
