package UpperCaseModule;

/**
* UpperCaseModule/UpperCaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperCase.idl
* Tuesday, 5 May, 2026 10:40:17 PM IST
*/

public final class UpperCaseHolder implements org.omg.CORBA.portable.Streamable
{
  public UpperCaseModule.UpperCase value = null;

  public UpperCaseHolder ()
  {
  }

  public UpperCaseHolder (UpperCaseModule.UpperCase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UpperCaseModule.UpperCaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UpperCaseModule.UpperCaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UpperCaseModule.UpperCaseHelper.type ();
  }

}
