package UpperCaseModule;


/**
* UpperCaseModule/UpperCaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperCase.idl
* Tuesday, 5 May, 2026 10:40:17 PM IST
*/

public interface UpperCaseOperations 
{
  String ConvertToUppercase (String input);
} // interface UpperCaseOperations
